services:
  database:
    image: postgres:latest
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ${PWD}/data/db/:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ${PWD}/data/pgadmin/:/var/lib/pgadmin/
