spring:
  application:
    name: amaranth
  docker:
    compose:
      enabled: false
      file: compose.dev.yaml
      readiness:
        wait: ONLY_IF_STARTED
discord:
  testGuildID: 1425009895765446728